### PR TITLE
Add deadlines to "project phase" table

### PR DESCRIPTION
**Pull request by DenisHromada**
Duplicate deadline information to project phase table to improve readability.  Table format matches [2020 tag](https://github.com/nesfit/ICS/tree/2020).

### CODE REVIEW

**Comment by pluskal** [comment]
Thanks for the PR! I appreciate your effort in making this contribution.

Contrary to your suggestion, I prefer not to duplicate this information. It was this way in the past, but keeping all the dates in sync is challenging. These dates are in the IS in the table overview above. Putting them here would introduce a third copy, ultimately breaking a Single source of truth (SSOT) rule not once but thrice.

Let's put this to vote on tomorrow's lecture and seek public opinion.

**Comment by DenisHromada** [comment]
Understandable. The issue with duplication crossed my mind aswell, but I wanted to minimise my changes. As an alternative to duplicating the dates inside README.md I suggest the following:
- Rename "Plán semestru" -> "Harmonogram přednášek" (or a more descriptive name given the following modification)
- Remove project deadlines from what used to be "Plán semestru"
- Add deadline information to project phase table.

**Comment by pluskal** [comment]
Like [this](https://github.com/nesfit/ICS/tree/2efac460e642e95af541bfac95c3ba38ebcbba48#projekt)?

I preferred to keep lectures, demos, and deadlines separate, but this merger was made as a reaction to student feedback.

**Comment by DenisHromada** [comment]
Huh. Seems like you can't please everyone. In the end it doesnt matter that much. I and a couple of my teammates just struggled to find the project deadlines at first glance. Either way, my whole project deadline localization issue was solved when I sent the deadlines into our teams comms and pinned the message.

If I were to make a case for my suggestion, there would be two tables. One with lessons and demos and one with project deadlines. 
From my point of view having lectures and demos separate doesnt make as much sense, since they typically compliment eachother. Whereas project deadlines are more or less disconnected from them.  
When I am looking at a subjects schedule I am typically: 
- looking for what following lectures/demos will be about 
**OR**
- working on a project and wondering how much time I have left

But as I already said. Any way is fine as long as all information is available, which it currently is.

**Pull request closed without merging**
